databases:
  - name: budgetApp
    databaseName: budgetapp_b6vh
    user: budgetapp_b6vh_user

services:
  - type: web
    name: budgetApp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp_b6vh
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false